AWSTemplateFormatVersion: '2010-09-09'
Description: Create an EC2 instance with Auto Scaling

Resources:
  MyLaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: ami-0c55b159cbfafe1f0  # Replace with your Ubuntu 20.04 AMI ID
      InstanceType: t2.micro
      KeyName: your-key-pair-name  # Replace with your key pair name
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash
            # Update the package list and install build dependencies
            sudo apt-get update -y
            sudo apt-get install -y build-essential autoconf m4 libncurses5-dev libssh-dev unixodbc-dev libssl-dev

            # Download and build Erlang/OTP 20.3 from source
            sudo wget https://github.com/erlang/otp/archive/OTP-20.3.tar.gz
            tar xzf OTP-20.3.tar.gz
            cd otp-OTP-20.3
            sudo ./otp_build autoconf
            sudo ./configure
            sudo make && sudo make instal

  MyAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      LaunchConfigurationName:
        Ref: MyLaunchConfiguration
      MinSize: 1
      MaxSize: 4
      DesiredCapacity: 2
      VPCZoneIdentifier:
        - subnet-12345678  # Replace with your subnet IDs
        - subnet-87654321  # Replace with your subnet IDs
      AvailabilityZones:
        - us-east-1a  # Replace with your AZs
        - us-east-1b  # Replace with your AZs
      Tags:
        - Key: Name
          Value: MyAutoScalingInstance
          PropagateAtLaunch: true